In [1]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape  # arrayオブジェクトのshape属性 (@property)

(2, 3)

In [5]:
a.ndim  # 2次元の配列

2

In [6]:
a.dtype  # 中身のデータ型

dtype('int64')

In [7]:
a.size  # 要素数

6

In [8]:
np.arange(0, 20, 4)

array([ 0,  4,  8, 12, 16])

In [9]:
np.arange(0, 2.1, 0.3)  # float(浮動小数点数)は近似値であるため、2.1も含まれてしまった

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1])

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((2, 3), dtype=np.int16)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [12]:
np.linspace(0, 2, 9)  # linearly spaced: 比例: 等間隔

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [15]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
# 準備
x = np.arange(0, 10, 2)
y = np.arange(5)
z = np.arange(0, 100, 20)
print(x, y, z)

[0 2 4 6 8] [0 1 2 3 4] [ 0 20 40 60 80]


In [17]:
np.append(x, y)

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [18]:
np.hstack([x, y, z])

array([ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4,  0, 20, 40, 60, 80])

In [19]:
np.vstack([x, y, x])

array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [20]:
# 準備
a = np.arange(10, 51, 10)
b = np.arange(1, 6)
print(a, b)

[10 20 30 40 50] [1 2 3 4 5]


In [21]:
a - b

array([ 9, 18, 27, 36, 45])

In [22]:
a < 30

array([ True,  True, False, False, False])

In [23]:
a = np.random.random((2, 3))  # numpyのrandomモジュールのrandom関数
a

array([[0.82200246, 0.09622261, 0.80892482],
       [0.94269005, 0.63520932, 0.15666801]])

In [24]:
a = np.arange(1, 11)
a.sum()

55

In [25]:
a.mean()

5.5

In [26]:
print(a.max(), a.min())

10 1


In [27]:
a = np.arange(1, 11).reshape(2, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
a.sum(axis=0)

array([ 7,  9, 11, 13, 15])

In [29]:
a.sum(axis=1)

array([15, 40])

In [30]:
# 準備
a = np.arange(1001)
a

array([   0,    1,    2, ...,  998,  999, 1000])

In [31]:
np.set_printoptions(threshold=1001)  # 表示の上限を(デフォの1000個から)1001個に変更
a

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
         55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
         66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
         77,   78,   79,   80,   81,   82,   83,   84,   85,   86,   87,
         88,   89,   90,   91,   92,   93,   94,   95,   96,   97,   98,
         99,  100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
        110,  111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
        121,  122,  123,  124,  125,  126,  127,  128,  129,  130,  131,
        132,  133,  134,  135,  136,  137,  138,  139,  140,  141,  142,
        143,  144,  145,  146,  147,  148,  149,  1